apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: petclinic-db
  namespace: default
  labels:
    app: petclinic-db
spec:
  selector:
    matchLabels:
      app: petclinic-db
  serviceName: petclinic-db
  template:
    metadata:
      labels:
        app: petclinic-db
    spec:
      containers:
        - name: petclinic-db
          image: quay.io/sololabs/petclinic-db:v2
          ports:
            - containerPort: 3306
              protocol: TCP
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "petclinic"
            - name: MYSQL_DATABASE
              value: "petclinic"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: sql-data
      volumes:
        - name: sql-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-db
  namespace: default
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: petclinic-db
  type: ClusterIP
